// Note : The id for this object is randomly generated by Firebase Realtime Database
class Activity {
  String id, activityType, institution, objective, remarks, result;
  DateTime when;

  Activity({
    required this.id,
    required this.activityType,
    required this.institution,
    required this.when,
    required this.objective,
    required this.remarks,
    required this.result,
  });

  Map<String, dynamic> toJson() => {
        "activityType": activityType,
        "institution": institution,
        "when": when.toString(),
        "objective": objective,
        "remarks": remarks,
        "result": result,
      };

  bool get isEmpty =>
      id.isNotEmpty &&
      activityType.isNotEmpty &&
      institution.isNotEmpty &&
      when.toString().isNotEmpty &&
      objective.isNotEmpty &&
      remarks.isNotEmpty &&
      result.isNotEmpty;

  factory Activity.fromJson(Map<String, dynamic> json) => Activity(
        id: json['id'],
        activityType: json['activityType'],
        institution: json['institution'],
        when: DateTime.parse(json['when']),
        objective: json['objective'],
        remarks: json['remarks'],
        result: json['result'],
      );

  factory Activity.createNew({
    required String activityType,
    required String institution,
    required DateTime when,
    required String objective,
    required String remarks,
  }) =>
      Activity(
        id: '',
        activityType: activityType,
        institution: institution,
        when: when,
        objective: objective,
        remarks: remarks,
        result: '',
      );

  factory Activity.empty() => Activity(
        id: '',
        activityType: '',
        institution: '',
        when: DateTime.now(),
        objective: '',
        remarks: '',
        result: '',
      );
}
