// Note : The id for this object is randomly generated by Firebase Realtime Database
class Activity {
  String id, activityType, institution, when, objective, remarks, result;

  Activity({
    required this.id,
    required this.activityType,
    required this.institution,
    required this.when,
    required this.objective,
    required this.remarks,
    required this.result,
  });

  Map<String, dynamic> toJson() => {
        "id": id,
        "activityType": activityType,
        "institution": institution,
        "when": when,
        "objective": objective,
        "remarks": remarks,
        "result": result,
      };

  factory Activity.fromJson(Map<String, dynamic> json) => Activity(
        id: json['id'],
        activityType: json['activityType'],
        institution: json['institution'],
        when: json['when'],
        objective: json['objective'],
        remarks: json['remarks'],
        result: json['result'],
      );

  factory Activity.createNew({
    required String activityType,
    required String institution,
    required String when,
    required String objective,
    required String remarks,
  }) =>
      Activity(
        id: '',
        activityType: activityType,
        institution: institution,
        when: when,
        objective: objective,
        remarks: remarks,
        result: '',
      );
}

// Note : Default value for object when data has not been obtained from API
class UninitializeActivity extends Activity {
  UninitializeActivity()
      : super(
          id: '',
          activityType: '',
          institution: '',
          when: '',
          objective: '',
          remarks: '',
          result: '',
        );
}
